### PR TITLE
ShaderSystem and BackgroundShader.

### PR DESCRIPTION
**Pull request by RotaruDan**

### CODE REVIEW

**Comment by anserran** [comment]
Revised.

**Comment by RotaruDan** [comment]
I need BackgroundShader component to be able to treat specially the model entities that have it. Those entities shouldn't be touchable nor appear in front of others.

**Comment by RotaruDan** [comment]
All comments addressed.

**Comment by anserran** [comment]
All set, but 1 final thing, I think you forgot to upload the zip with the shaders corrected. Feel free to merge once is done.

**Comment by RotaruDan** [comment]
Yeah my bad!

**Pull request merged**
