### PR TITLE
Templates UI

### PR DESCRIPTION
**Pull request by gorco**

### CODE REVIEW

**Comment by anserran** [comment]
Revised.

**Comment by gorco** [comment]
Simplified, comments addressed in new commits. If you want I can redo all commits to clean the history

**Comment by anserran** [comment]
Great! Revised. Yes, a rebase would help.

**Comment by gorco** [comment]
Rebased and changed the layout of AttributeMenu.class to simplify calculations

**Comment by anserran** [comment]
Great. Only 1 tiny detail. Feel free to merge once is done.

**Pull request merged**
