### PR TITLE
Repo playground robots

### PR DESCRIPTION
**Pull request by jtorrente**
Full TimeMokapsule library + a few enhancements regarding the repo-builder, here and there.

If you want to try and run the generation of the library, make sure to have installed ImageMagick and generate the engine-desktop-with-dependencies file

### CODE REVIEW

**Comment by jtorrente** [comment]
I think this PR is ready for merging. Could anyone take a quick look at it? I'd need to have this merged before I get to submit the bubbles and the animals library

**Comment by RotaruDan** [comment]
It seems that there is a compilation failure.

**Comment by jtorrente** [comment]
Thanks for the tip. Fixed now

**Comment by RotaruDan** [comment]
Very nice addition, just one minor question pending.

**Comment by jtorrente** [comment]
OK - don't think any tween is missing so perhaps ready for merge?

**Pull request merged**
