### PR TITLE
Standalone mokaps

### PR DESCRIPTION
**Pull request by jtorrente**
Added functionality to export mokaps as standalone self-contained APKs. Only engine is embedded via Maven.

For this to work properly, it is necessary to have installed correct versions of the ead artifacts, so don't forget to `mvn clean install` before testing it (otherwise it fetches the artifacts from remotes, which do not contain the Activity this pr requires).

I've used Game Of Thrones for testing and demonstration. The generated apk looks like this: https://dl.dropboxusercontent.com/u/3006702/got.apk. You will notice that transitions make a nasty scale down effect. Any ideas why this may be happening?

### CODE REVIEW

**Comment by RotaruDan** [comment]
It seems that, somehow, we've managed to fix that bug only for the editor but not for the engine. Maybe we did something to the engine displayed in the editor but not to the "raw" engine.

**Comment by RotaruDan** [comment]
Very nice addition, some minor things pending.

As for the transitions bug, I think that we may need to do something like we did here: https://github.com/e-ucm/ead/commit/25ae670b35743e018ba312cc2cba7e55960479e2#diff-dbfe373b68f331fdbc0e8d94ce96f7b0R37 to the DefaultGameView#layout() method, I'm not completely sure about this, and I can't try it at the moment because I'm not home.

**Comment by jtorrente** [comment]
I've addressed all comments, I think, but Reference comp. management. As soon as I get clarified on this (see comment above) I will also integrate it into the Exporter.

I've also created an issue and self-assigned (https://github.com/e-ucm/ead/issues/949) to check the engine layout. Thanks for pointing me in the right direction, @RotaruDan, it helps knowing that this is a bug fixed some time ago in mokap editor.

**Comment by RotaruDan** [comment]
OK, feel free to merge this pr if you need it, otherwise I would like to leave it open atleast untill the transition bug is fixed.

**Comment by jtorrente** [comment]
I found a way to solve the problem with bad size management in transitions. The problem is that I cannot get it working both for engine and editor at the same time, so I had to make GoSceneExecutor flexible to determine the best way to calculate screenWidth and screenHeight: https://github.com/jtorrente/ead/commit/8c87a50073baadc2574b1fbf92e68b9603ef60e2

I'd like to see what you guys @RotaruDan and @anserran think about this solution.

I also had to change the maven wrapper I was using since it was making DEX compiler crush abruptly when compiling mokap-android. I've struggled my mind for hours trying to find out why in hell editor-exporter had any effect at all on mokap/android compile lifecycle, since it did not make any sense to me. But it happens that editor/exporter is referenced by editor/core, and editor/core is referenced by mokap/core. That makes me think we should refactor Exporter and add it to Platform, so we'd have an ExporterAndroid and an ExporterDesktop, plus ExporterApplication. I'd also like to know what you think about this.

**Comment by anserran** [comment]
About transitions, we can go with this fix. Although I think the real problem is that we should use actors instead of frame buffers for transitions. We need them in the editor, maybe when they're ready we can also use them in the engine.

About the structure and the maven projects (without revising the complete PR), have you considered just generating the apk directly with maven (instead of invoking it from Java)? We had maven embedded because we wanted the user to create apks from the editor in eAdventure, but that is no longer the case.

**Comment by jtorrente** [comment]
So, since we all seem to agree that this solution may do for now, can we just merge it?

**Comment by RotaruDan** [comment]
Yes. Merging.

**Pull request merged**
