### PR TITLE
Link node builder

### PR DESCRIPTION
**Pull request by RotaruDan**

### CODE REVIEW

**Comment by RotaruDan** [comment]
There seems to be a problem with the Switch widget withing a ScrollPane in my mobile that doesn't allow the user to trigger a change in its state. On the other hand, works fine on the desktop.

I'll investigate this bug with more detail.

**Comment by gorco** [comment]
when I set a goScene initBehavior and then use the play button in that scene, the next exception is throw

```java
GameView: GameView has a child that does not belong to an EngineEntity or its user object is not set.
EditorApplicationListener: Fatal error: LWJGL Application(10)
java.lang.NullPointerException
	at es.eucm.ead.engine.systems.effects.transitions.TransitionManager$TransitionFrame.updateTexture(TransitionManager.java:181)
	at es.eucm.ead.engine.systems.effects.transitions.TransitionManager.draw(TransitionManager.java:141)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:117)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:117)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:117)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at es.eucm.ead.editor.view.builders.scene.play.TestGameView.drawChildren(TestGameView.java:72)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at es.eucm.ead.editor.EditorApplicationListener.render(EditorApplicationListener.java:133)
	at es.eucm.ead.editor.MokapApplicationListener.render(MokapApplicationListener.java:100)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

**Comment by gorco** [comment]
Revision done, some comments pending

**Comment by RotaruDan** [comment]
All comments addressed.

**Comment by gorco** [comment]
Great

**Pull request merged**
