### PR TITLE
Spinerobots demos

### PR DESCRIPTION
**Pull request by jtorrente**
This PR changes the type of batch used in the engine so spine animations work

### CODE REVIEW

**Comment by jtorrente** [comment]
Just a little context - I'm experiencing issues trying to get the robots implemented with Spine to work in the engine. I could only make the white robot to work, as for the others I keep getting this exception:

```java
java.lang.RuntimeException: PolygonSpriteBatch is required to render meshes.
	at com.esotericsoftware.spine.SkeletonRenderer.draw(SkeletonRenderer.java:146)
	at es.eucm.ead.engine.components.renderers.SpineAnimationComponent.draw(SpineAnimationComponent.java:75)
	at es.eucm.ead.engine.entities.actors.RendererActor.drawChildren(RendererActor.java:73)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:71)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:71)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:71)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:71)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at es.eucm.ead.engine.entities.actors.EntityGroup.draw(EntityGroup.java:71)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:154)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at es.eucm.ead.engine.EngineApplicationListener.render(EngineApplicationListener.java:144)
	at com.badlogic.gdx.backends.lwjgl.LwjglCanvas$3.run(LwjglCanvas.java:240)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I've uploaded the demos I created so you can also have a look into it if you like

**Comment by RotaruDan** [comment]
That sounds like it needs PolygonSpriteBatch instead of the default SpriteBatch in order to draw some robots.

The PolygonSpriteBatch is a more powerful renderer that can process all type of polygons. Probably those robots have some type of advanced animation only displayable by the PolygonSpriteBatch.

**Comment by jtorrente** [comment]
Thanks for the tip. I tried using PlygonSpriteBatch but does not solve the problem. I had a quick look at the code and it looks like the exception message is misleading:
```java
if(attachment instanceof MeshAttachment || attachment instanceof SkinnedMeshAttachment) {
                    throw new RuntimeException("PolygonSpriteBatch is required to render meshes.");
                }
```
As you see, it is not checking if batch is actually an instance of PolygonSpriteBatch or anything else.

**Comment by anserran** [comment]
Everything OK, but we should also use a PolygonSpriteBatch in the editor also.

**Comment by jtorrente** [comment]
Done - PolygonSpriteBatch also used in editor

**Pull request merged**
