### PR TITLE
SoundImageOrg repo library.

### PR DESCRIPTION
**Pull request by RotaruDan**

### CODE REVIEW

**Comment by jtorrente** [comment]
Reviewing

**Comment by jtorrente** [comment]
Revision done. This is actually very cool! Any piece of content greatly improves with some sound.

Two comments pending: 
1) Add Spanish tags (see above)
2) I'd strongly suggest placing names and descriptions within the code instead of in external files within the zip file. Basically, because it makes it more difficult to check/revise/maintain them

**Comment by RotaruDan** [comment]
All comments addressed.

**Comment by jtorrente** [comment]
Nice!

**Pull request merged**
